// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhZbOjqZIYyqFxqm0mY6d2Pg0lm2stFhA',
    appId: '1:57288734777:web:fbede16e7a65b07b03f5e8',
    messagingSenderId: '57288734777',
    projectId: 'chat-app1-89014',
    authDomain: 'chat-app1-89014.firebaseapp.com',
    storageBucket: 'chat-app1-89014.appspot.com',
    measurementId: 'G-4WBJ15GDKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWf1F5GqJkMG4jVEzTThWMSwXIPkKtUU',
    appId: '1:57288734777:android:36a3b46ac4a9b99a03f5e8',
    messagingSenderId: '57288734777',
    projectId: 'chat-app1-89014',
    storageBucket: 'chat-app1-89014.appspot.com',
  );
}
